### ISSUE TITLE
Newest version (0.67.0) stalls when querying directions

### ISSUE THREAD

**Issue by nicholashead** [maximn/google-maps#105]
Not sure what changed between 0.66.0 and 0.67.0 - but we have very simple "look up directions" code that calls `GoogleMaps.Directions.Query` - and since upgrading to 0.67.0, it just "sits there" and never returns/timeouts. Downgrading to 0.66.0 fixes the issue for us.

**Comment by maximn** [comment]
Sample code/test to reproduce? .NET version?

**Comment by MattLugar** [comment]
I have the same issue.  It works fine in a console application but it sits and spins in a ASP.NET web forms site.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using GoogleMapsApi;
using GoogleMapsApi.Entities.Directions.Request;
using GoogleMapsApi.Entities.Directions.Response;

public partial class test : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        DirectionsRequest directionsRequest = new DirectionsRequest()
        {
            Origin = "NYC, 5th and 39",
            Destination = "Philladephia, Chesnut and Wallnut",
        };

        DirectionsResponse directions = GoogleMaps.Directions.Query(directionsRequest);
        Response.Write(directions);
    }
}
```

If I go into debug mode the best I can get for debugging is this in intermediate window:
```
DirectionsResponse test = GoogleMaps.Directions.Query(directionsRequest);
Evaluation of method GoogleMapsApi.EngineFacade`2[[GoogleMapsApi.Entities.Directions.Request.DirectionsRequest, GoogleMapsApi, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null],[GoogleMapsApi.Entities.Directions.Response.DirectionsResponse, GoogleMapsApi, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].Query requires calling method System.RuntimeType.IsEnumDefined, which cannot be called in this context.

```

**Comment by stefanolson** [comment]
Same issue here - if I go back to 0.66 all works. I can see from fiddler the request is being sent and the response received but it is hanging. however, using QueryAsync does work correctly.

**Comment by tipstrade** [comment]
I try to avoid "Me too", but me too. Rolling back 0.66 solves the problem

Target Framework = .Net Framework 4.6
NewtonSoft.Json v.10.0.3

**Comment by maximn** [comment]
I moved to MAC so on my machine it works (mono). Will try to find a Windows machine that I can reproduce it on.

**Comment by maximn** [comment]
Do you have the problem only for directions or all other methods as well?

**Comment by maximn** [comment]
Do you have the problem only with directions or all other methods as well?

**Comment by oobayly** [comment]
I'll put together a project targeting multiple frameworks and test various methods and get back to you.

**Comment by tipstrade** [comment]
Right, I created a console app (net46) it Geocoding, Map URL generation and Directions work fine, which lead me to believe it could be deadlocks.

I then created a new Windows Forms (net46) app and the app stalls on the GoogleMaps.Geocode.Query call, so it's not just directions, and made me pretty sure it's a deadlock.

So, I converted the Query calls to QueryAysnc, and they worked fine from either an aysnc event handler, or ContinueWith. Rather than trying to explain it, it's best to have a look at this article: [Await, and UI, and deadlocks! Oh my!
](https://blogs.msdn.microsoft.com/pfxteam/2011/01/13/await-and-ui-and-deadlocks-oh-my/)

The problem is that the Query methods internally call the QueryAsync methods and use Task.Result to fetch the result. This causes the deadlock. So, if you're using Windows Forms, don't use the Synchronous methods, use the Async methods and do the async handling yourself.

**Comment by maximn** [comment]
Looks like I found the problem.
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

Published v0.68.0 just now. Please let me know if the problem is solved.

**Comment by tipstrade** [comment]
Afraid it's still not working - the problem with the ConfigureAwait(false) option is that it needs to be used [all the way down](https://en.wikipedia.org/wiki/Turtles_all_the_way_down).

From what you said, if you're using Mono this may not be something you can test, so I've forked and will have a look at whether I can fix it and post a PR.

**Comment by maximn** [comment]
Because the code that calls it blocks (request.Result) I thought that it
might help. I'll be happy to get a PR that solves it. Thanks a lot!

*-- Maxim.*

**Comment by nicholashead** [comment]
Unfortunately the issue is still happening with .69

**Comment by peterdew** [comment]
Thanks a lot. Used the async method and changed all methods in the chain to by async, that fixed it.
