### ISSUE TITLE
Update to V 0.7 from .66 stopped working 

### ISSUE THREAD

**Issue by sstasevich** [maximn/google-maps#111]
We do not even get a response from the server to see what is going on.
  {
                        Origin = origin,
                        Destination = destination
                    };

                    DirectionsResponse directions = GoogleMaps.Directions.Query(directionsRequest);

I am assuming there are updates related to use of API key, we did not have to pass the key before, not sure if that is what is causing the issue.
Documentation does not reflect any breaking changes.
Test with passing and ApiKey produces same results
             DirectionsRequest directionsRequest = new DirectionsRequest()
                    {
                        Origin = origin,
                        Destination = destination,
                        ApiKey = "...."
                    };

**Comment by maximn** [comment]
See this - 
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

You'll have to use `.ConfigureAwait(false)`

Let me know if it solves your problem.

**Comment by maximn** [comment]
Please let me know if it worked after you try. You can read the full details in the blog post that I've shared.
