### ISSUE TITLE
A query on Directions hangs

### ISSUE THREAD

**Issue by peterdew** [maximn/google-maps#115]
My code just  hangs on this line. Never getting a response back.  
![image](https://user-images.githubusercontent.com/27804639/44143062-870b7d38-a082-11e8-819d-9a55481de897.png)

The request is arriving at google maps, I can see the request and the responsecode (http 200 ok))
What can be the reason here?

**Comment by maximn** [comment]
Are you using the latest version? Is it a web/desktop?

**Comment by maximn** [comment]
See if this helps - https://github.com/maximn/google-maps/issues/105

**Comment by JohnMcAvinue** [comment]
Still happening for me on 0.72 using .Net 4.5.2. 

My code isn't Async but I tried using QueryAsync and then .Result but it never return a result.

Reverting to version 0.66 fixed the problem.

**Comment by maximn** [comment]
Did you use `.ConfigureAwait(false)` ?
https://github.com/maximn/google-maps/issues/111

**Comment by JohnMcAvinue** [comment]
No I didn't but will try and let you know. Thanks

**Comment by wrighthinsdale** [comment]
Hey maximn, I can confirm what John also said. For my project, the latest version just HUNG when doing geocodes. Oddly, it worked fine from within a CONSOLE application, but hung when I was using the web api controllers. This behavior occurred regardless of whether I used async or not. When I rolled back to an earlier version (0.66) it worked fine. I should mention I also tried it with 0.68 and 0.70. No success there, either.

**Comment by maximn** [comment]
Can you please try with v 0.75.0? Can you try both blocking and async methods?

**Comment by oliverchristen** [comment]
I both tested Query() and QueryAsync() in a web application and both are working fine without blocking (deadlock). v0.75.0 seems to be fine.

**Comment by oliverchristen** [comment]
As you see on the thread it works fine. Thaks for the immediate merge!

Best regards,
Oliver

Von: Maxim Novak
Gesendet: Donnerstag, 30. August, 13:48
Betreff: Re: [maximn/google-maps] A query on Directions hangs (#115)
An: maximn/google-maps
Cc: Subscribed


Can you please try with v 0.75.0? Can you try both blocking and async methods?
