### ISSUE TITLE
Add Vehicle Type LONG_DISTANCE_TRAIN

### ISSUE THREAD

**Issue by oliverchristen** [maximn/google-maps#118]
The google maps directions API call 
https://maps.googleapis.com/maps/api/directions/json?&mode=transit&origin=Z%C3%BCrich-Flughafen&destination=Z%C3%BCrich&departure_time=1534606200
returns directions containing a vehicle type **LONG_DISTANCE_TRAIN**. This leads to an exception when parsing the response. When parsing this string to a VehicleType enum an ArgumentException occurs.

This error is reproducible like this:
`GoogleMapsApi.GoogleMaps.Directions.Query(new DirectionsRequest
            {
                Origin = "Zürich-Flughafen",
                Destination = "Zürich",
                TravelMode = TravelMode.Transit,
                DepartureTime = new DateTime(2018, 08, 18, 15, 30, 00),
            });`

Unfortunetely the vehicle type LONG_DISTANCE_TRAIN is not documented here: https://developers.google.com/maps/documentation/directions/intro#VehicleType

**Comment by maximn** [comment]
Nuget v0.74.0
