### ISSUE TITLE
APIKey Test programm not working

### ISSUE THREAD

**Issue by HSchmidt2018** [maximn/google-maps#123]
I have placed my (working APIKey) in the app.config of MapsApiTest.csproj and GoogleMapsApi.Test.
On calling the method GoogleMaps.Directions.Query(drivingDirectionRequest) in line 29 of Program.cs I get the error:

**"You have exceeded your rate-limit for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_"**

What is wrong ? Can you help me ?
Thank you

**Comment by maximn** [comment]
Here's a working sample - 
https://github.com/maximn/google-maps/blob/master/GoogleMapsApi.Test/app.config#L8
