### ISSUE TITLE
Support sessionToken parameter in Places API?

### ISSUE THREAD

**Issue by afroewis** [maximn/google-maps#124]
Great repository, thank you! 

I would like to use the Place API using this library and I noticed that the library, `PlaceAutocompleteRequest` to be exact, does not support the `sessionToken` parameter. 

From the Places Autocomplete docs (https://developers.google.com/places/web-service/autocomplete):
*sessiontoken — A random string which identifies an autocomplete session for billing purposes. If this parameter is omitted from an autocomplete request, the request is billed independently. See the pricing sheet for details.*

I think it would make a lot of sense to support this parameter. It would be important for my application. 

Shall I create a PR for this feature?

**Comment by maximn** [comment]
Sure, go ahead and submit a RP
