### ISSUE TITLE
Supporting .net core

### ISSUE THREAD

**Issue by flopez2904** [maximn/google-maps#134]
Support for .net core is available?

**Comment by bergbria** [comment]
I coded up an initial PR: #136

**Comment by gguillen** [comment]
@flopez2904 My PR that was merged a few days ago adds support for .net core.

**Comment by maximn** [comment]
You can build it locally but it's not available on NuGet yet. I'm working on fixing it :)

**Comment by maximn** [comment]
Published nuget v 1.0.0.
