### ISSUE TITLE
MapsAPIGenericEngine uses HttpClient incorrectly

### ISSUE THREAD

**Issue by stephajn** [maximn/google-maps#155]
The MapsApiGenericEngine creates a new HttpClient for every request it makes. As a result, under load, this library would burn up all of the available sockets on a machine because it is not reusing the same HttpClient instance.

This class should be updated so that the HttpClient is created once as a static instance instead.

**Comment by maximn** [comment]
This is resolved in v1.3.0 ! Thanks @stephajn
