### ISSUE TITLE
Place Details response is missing fields - permanently_closed, photos

### ISSUE THREAD

**Issue by AshD** [maximn/google-maps#36]
Thank you for this library.
In GoogleMapsApi/Entities/PlacesDetails/Response/Result.cs the following fields are missing. 
permanently_closed,
photos, 
scope 

From https://developers.google.com/places/documentation/details

Thanks,
Ash

**Comment by maximn** [comment]
Hi, I'll be glad to accept a pull request.

**Comment by meywd** [comment]
Place details response is still missing the fields:

- permanently_closed
- photos
