### ISSUE TITLE
Radar search support

### ISSUE THREAD

**Issue by rossiter10** [maximn/google-maps#37]
Edit: I made a pull request for this.

So it looks like the PlacesRequest uses maps.googleapis.com/maps/api/place/search/ which seems to act very similar to maps.googleapis.com/maps/api/place/nearbysearch.  What I'm looking for is the radar search (https://developers.google.com/places/webservice/search#RadarSearchRequests).  This allows you to search 200 places at once instead of the 20(or 60). Am I missing this somewhere, or are there any plans to add it?

**Comment by maximn** [comment]
PR that adds it mergeg now
