### ISSUE TITLE
Increace max Radius for PlacesAutocomplete from 50000 to 20000000 to turn off location bias

### ISSUE THREAD

**Issue by quasilatent** [maximn/google-maps#39]
The paragraph from [API documentation](https://developers.google.com/places/webservice/autocomplete#location_biasing) says:
> Note: If you do not supply the location and radius, the API will attempt to detect the user's location from their IP address, and will bias the results to that location. If you would prefer to have no location bias, set the location to '0,0' and radius to '20000000' (20 thousand kilometers), to encompass the entire world.

20k km is about a half of equator length therefore it is not artificial unlike 50000 limitation.

**Comment by maximn** [comment]
Hi, I'll be glad to accept a pull request.
