### ISSUE TITLE
Wrapper with Info Window

### ISSUE THREAD

**Issue by mythros** [maximn/google-maps#40]
Hello, I found your lib and want to try it out. 

I am trying to implement an info window, is there a wrapper in your lib with an Info window?

**Comment by maximn** [comment]
What is an info window? Can you provide a link to the description by google?

**Comment by rossiter10** [comment]
[InfoWindow link](https://developers.google.com/maps/documentation/javascript/infowindows)

mythros - This library is a wrapper for the web service. I don't believe there is any functionality for anything client side.

**Comment by maximn** [comment]
@rossiter10 is right. This library provides wrappers only for Google maps web services and Static maps.
