### ISSUE TITLE
Is that possible make your BaseUrl changeable from out side?

### ISSUE THREAD

**Issue by VisionZhao** [maximn/google-maps#45]
I love your GoogleMapApi, very easy to use,  My company has opensource project provide google style API which has no limitation for internal usage. use your code all I need change is change your MapsBaseRequest.cs BaseUrl parameter. I am thinking, is that possible make this field editable from outside, which give user ability to customize Url instead of only use maps.googleapis.com/maps/api/

**Comment by maximn** [comment]
Yes, you can make the BaseUrl
https://github.com/maximn/google-maps/blob/e621c2a20eeadc28109851cfee29a26939f79c6c/GoogleMapsApi/Entities/Common/MapsBaseRequest.cs#L54-L60

Be accessed from the outside (Like the ApiKey example).
Note that it should have the `google` base url as a default.

You're welcome to issue a pull request with this change.

**Comment by maximn** [comment]
Done. Available from version 0.43 on nuget.
