### ISSUE TITLE
Please add Travel Modes to Distance Matrix API

### ISSUE THREAD

**Issue by bbmaster** [maximn/google-maps#54]
Please add property Travel Modes to Distance Matrix API.
https://developers.google.com/maps/documentation/distance-matrix/intro#RequestParameters
Thx

**Comment by maximn** [comment]
You're welcome to issue a pull request if you'd like to.

**Comment by bbmaster** [comment]
Could you generate/publish a new NuGet package?

Thx,
Balázs

2016-04-07 18:04 GMT+02:00 Maxim Novak <notifications@github.com>:

**Comment by maximn** [comment]
What do you mean? There's still no fix for this issue.

**Comment by berinder** [comment]
This seems to be solved by
Commit 5da4653a
The-ChrisS <chris.smith.dev@gmail.com>
2016-08-24 10:43:54

So this Issue should be closed.
