### ISSUE TITLE
Convert to PCL for using in Xamarin

### ISSUE THREAD

**Issue by cdesewell** [maximn/google-maps#55]
Currently this projects NuGet package cant be used in a Xamarin.Android or Xamarin.IOS project. If changed to a PCL and given the right profile this could be fixed.

**Comment by maximn** [comment]
Not sure if it'll compile. Do you want to issue a pull request with the fix?

**Comment by cdesewell** [comment]
I had a go, Its dependence on System.Data creates complications.

**Comment by rhwilburn** [comment]
This should be closed, as .net standard is a better way of going (which is now supported). Can this be closed? @cdesewell
