### ISSUE TITLE
DurationInTraffic for Directions

### ISSUE THREAD

**Issue by bobyenser** [maximn/google-maps#56]
Is it possible to return DurationInTraffic for Directions service?  I only see it implemented for Distance Matrix Service.

It's part of the object google returns.  https://developers.google.com/maps/documentation/javascript/reference#DirectionsLeg

**Comment by maximn** [comment]
You're welcome to issue a pull request with this feature.

**Comment by HolisticDeveloper** [comment]
Looks like this was implemented by #78 and is available with v0.6.3 or later.

**Comment by maximn** [comment]
@HolisticDeveloper thanks. Closing the issue.
