### ISSUE TITLE
A lot of classes missing from package ?

### ISSUE THREAD

**Issue by Xyten** [maximn/google-maps#57]
Bear with me, since I'm only starting out to tinker with .NET and C# for a bit. But it seems that there are a lot of classes missing for this wrapper ?

I did a new C# console application in Vis Stud 2015 and used NuGet to install the wrapper. Afterwards I tried copy pasting the code in the wiki but it throws me an error on classes such as
 
``` DirectionsResponse directions = MapsAPI.GetDirections(directionsRequest); ```
``` // The name MapsApi doesnt exist in current context ```

and 

``` GeocodingEngine geocodingEngine = new GeocodingEngine();  ```
``` // The type or namespace GeocodingEngine could not be found```

Do I need additional depedencies to get the wrapper to work ?

ps: I'm using GoogleMapsApi.0.52.0 and I also tried googleMapsApi 0.42.0 from NuGet. Both unable to work because there are missing classes

Thank you

**Comment by maximn** [comment]
Are you using .NET/4.0 ?

**Comment by solmead** [comment]
Did you add the includes for the namespaces?

**Comment by Xyten** [comment]
@maximn I am using .NET Framework 4.5.2 according to Visual studio

@solmead For direction, I use
``` using GoogleMapsApi.Entities.Directions.Request;  ```
``` using GoogleMapsApi.Entities.Directions.Response; ``` 

For Geocoding, I use
``` using GoogleMapsApi.Entities.Geocoding.Request; ```
``` using GoogleMapsApi.Entities.Geocoding.Response; ```

I rely on visual studio to automatically include them for me

**Comment by maximn** [comment]
Feels like some wrong configuration in your project.

What's the error that you're getting exactly?

*-- Maxim.*

**Comment by Xyten** [comment]
@maximn It could be that there are wrong configurations in my project. I'm not too good at setting up C# projects.

The error I'm getting is because I cant seem to find the classes to use. 
```DirectionsResponse directions = MapsAPI.GetDirections(directionsRequest); ```

What should I be including to get this to work ?

**Comment by maximn** [comment]
What's is the error *EXACTLY* ?

**Comment by Xyten** [comment]
Complete Code:
```
using GoogleMapsApi.Entities.Directions.Request;
using GoogleMapsApi.Entities.Directions.Response;
using GoogleMapsApi.Entities.Geocoding.Request;
using GoogleMapsApi.Entities.Geocoding.Response;
using System;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            DirectionsRequest directionsRequest = new DirectionsRequest()
            {
                Origin = "NYC, 5th and 39",
                Destination = "Philladephia, Chesnut and Wallnut",
            };
            DirectionsResponse directions = MapsAPI.GetDirections(directionsRequest);
            Console.WriteLine(directions);
      
            GeocodingRequest geocodeRequest = new GeocodingRequest()
            {
                Address = "new york city",
            };

            GeocodingEngine geocodingEngine = new GeocodingEngine();
            GeocodingResponse geocode = geocodingEngine.GetGeocode(geocodeRequest);
            Console.WriteLine(geocode);
        }

    }
}
```

Errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'MapsAPI' does not exist in the current context	ConsoleApplication1	C:\Users\DESKTOP-3\documents\visual studio 
2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs	19	Active
Error	CS0246	
```

```
The type or namespace name 'GeocodingEngine' could not be found (are you missing a using directive or an assembly reference?)	ConsoleApplication1	C:\Users\DESKTOP-3\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs	28	Active
Error	CS0246	
```
```
The type or namespace name 'GeocodingEngine' could not be found (are you missing a using directive or an assembly reference?)	ConsoleApplication1	C:\Users\DESKTOP-3\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs	28	Active
```

**Comment by maximn** [comment]
Did you still didn't find the reason?

**Comment by gverbake** [comment]
MapsAPI is no longer there... working version attached

`            
using GoogleMapsApi;
using GoogleMapsApi.Entities.Common;
using GoogleMapsApi.Entities.Directions.Request;
using GoogleMapsApi.Entities.Directions.Response;
using GoogleMapsApi.Entities.Geocoding.Request;
using GoogleMapsApi.Entities.Geocoding.Response;
using GoogleMapsApi.StaticMaps;
using GoogleMapsApi.StaticMaps.Entities;

            //Static class use (Directions) (Can be made from static/instance class)
            DirectionsRequest directionsRequest = new DirectionsRequest()
            {
                Origin = "NYC, 5th and 39",
                Destination = "Philladephia, Chesnut and Wallnut",
            };

            DirectionsResponse directions = GoogleMaps.Directions.Query(directionsRequest);
            Console.WriteLine(directions);
            
            //Instance class use (Geocode)  (Can be made from static/instance class)
            GeocodingRequest geocodeRequest = new GeocodingRequest()
            {
                Address = "new york city",
            };
            var geocodingEngine = GoogleMaps.Geocode;
            GeocodingResponse geocode = geocodingEngine.Query(geocodeRequest);
            Console.WriteLine(geocode);

            // Static maps API - get static map of with the path of the directions request
            StaticMapsEngine staticMapGenerator = new StaticMapsEngine();

            //Path from previos directions request
            IEnumerable<Step> steps = directions.Routes.First().Legs.First().Steps;
            // All start locations
            IList<ILocationString> path = steps.Select(step => step.StartLocation).ToList<ILocationString>();
            // also the end location of the last step
            path.Add(steps.Last().EndLocation);

            string url = staticMapGenerator.GenerateStaticMapURL(new StaticMapRequest(new Location(40.38742, -74.55366), 9, new ImageSize(800, 400))
            {
                Pathes = new List<GoogleMapsApi.StaticMaps.Entities.Path>(){ new GoogleMapsApi.StaticMaps.Entities.Path()
                {
                        Style = new PathStyle()
                        {
                                Color = "red"
                        },
                        Locations = path
                }}
            });
            Console.WriteLine("Map with path: " + url);
`

**Comment by gverbake** [comment]
Maybe update the sample code in wiki

**Comment by maximn** [comment]
updated readme.

**Comment by NethajiDuvarakanathan** [comment]
Where can i find dll for GoogleMapsApi / DirectionsRequest ? 
Since i get error , 
Error	10	The type or namespace name 'DirectionsRequest' could not be found (are you missing a using directive or an assembly reference?)	
Error	14	The type or namespace name 'GoogleMapsApi' could not be found (are you missing a using directive or an assembly reference?)	

Kindly help me.

**Comment by NethajiDuvarakanathan** [comment]
Here is the code:
GoogleMapsApi.Entities.Directions.Response.Leg leg = directionsResponse.Routes.ElementAt(0).Legs.ElementAt(0);

Error:
Error	2	'System.Collections.Generic.IEnumerable<GoogleMapsApi.Entities.Directions.Response.Route>' does not contain a definition for 'ElementAt' and no extension method 'ElementAt' accepting a first argument of type 'System.Collections.Generic.IEnumerable<GoogleMapsApi.Entities.Directions.Response.Route>' could be found (are you missing a using directive or an assembly reference?)	

Pls kindly suggest me some solution

**Comment by maximn** [comment]
Maybe you're using wrong version of the .NET Framework?
