### ISSUE TITLE
GeocodingRequest missing filter components

### ISSUE THREAD

**Issue by Silmas** [maximn/google-maps#60]
The original geocode Google api offers a filter (components) to get only certain types of components in the result.
I miss this parameter in the GeoCodingRequest class.

**Comment by suresh-dev** [comment]
GeocodingRequest geoCodingRequest = new GeocodingRequest
            {
                ApiKey = apiKey,
                Address = address

            };
am getting "REQUEST_DENIED" in GoogleMaps.Geocode.Query(geoCodingRequest);
could some one point me where am doing wrong ?

**Comment by Silmas** [comment]
Your API-Key is invalid.
Just look at:
[http://stackoverflow.com/questions/11231457/google-geocode-api-request-denied-in-json-response-reverse-geocode-action]

**Comment by berinder** [comment]
This was solved in Commit 9f307165 2016-09-05 and can be closed.
