### ISSUE TITLE
Static Map Requests now Require API Key?

### ISSUE THREAD

**Issue by AzumaRD** [maximn/google-maps#61]
I have updated to the 0.5.4 version of the GoogleMapsApi nuget package and today noticed something strange. I now get this message:

The Google Maps API server rejected your request. This service requires an API key.

For a URL that is built by the StaticMapsEngine:

http://maps.google.com/maps/api/staticmap?center=755%20Bush%20%23A%2C%20San%20Francisco%2C%20CA%2094108%20&zoom=14&size=350x350&maptype=roadmap&markers=color%3Ared%7Clabel%3AX%7C755%20Bush%20%23A%2C%20San%20Francisco%2C%20CA%2094108%20&sensor=false

But I see no way to add the API Key to the Static Map Request. Am I missing something new?

Thank you,
Ray

**Comment by maximn** [comment]
For the URL you posted I do see the static map. I guess you reached some kind of requests limit.

I think it's something new with their API, when the library was build wasn't a key.

If you want, you're welcome to issue a pull requests with adding an optional api key(I guess this can increase the limit.).
Here's the doc by google of how to add and API key - https://developers.google.com/maps/documentation/static-maps/
