### ISSUE TITLE
DirectionsResponse pass though to client for map rendering

### ISSUE THREAD

**Issue by lukejp1987** [maximn/google-maps#64]
Hi,

Within a MVC project is it possible to pass through the response from GoogleMapsApi.GoogleMaps.Directions.Query (DirectionsResponse) to a view to render on a map? I have tried to do this but the DirectionsResponse is not accepted by the google maps api's directionsDisplay.setDirections function.

Thanks

Luke

**Comment by maximn** [comment]
This question seems to be related to an MVC project, I'm not so familiar with ....

**Comment by lukejp1987** [comment]
It is an MVC project but would you know if the results from the GoogleMapsApi.GoogleMaps.Directions.Query (DirectionsResponse) could be passed through to a javascript function?

**Comment by maximn** [comment]
You need to convert it to a json which I assume that MVC project does for
you, but not sure ...

*-- Maxim.*

**Comment by rossiter10** [comment]
It sounds like you probably want to use the [javascript API](https://developers.google.com/maps/documentation/javascript/) instead if you are going to be doing anything in your view.

[Directions Service](https://developers.google.com/maps/documentation/javascript/directions)

**Comment by lukejp1987** [comment]
For the purpose of the project I'm working on I need to store the results from the Directions API and then reuse them later, I therefore need to pass the results through to view for the map to use when rendering the routes but the response from the API causes the google directionsDisplay.setDirections to return an error of "setDirections: in property routes: not an Array"

**Comment by rossiter10** [comment]
Yeah, so you'll probably need to do your directions call with the javascript api and you will then pass that result to setDirections().  You probably can't use the server side object(DirectionsResponse), even if you serialize it.

Check out [this example](https://developers.google.com/maps/documentation/javascript/examples/directions-simple) that uses the javascript API .
