### ISSUE TITLE
Google are deprecating multiple types for Place Searches

### ISSUE THREAD

**Issue by alowdon** [maximn/google-maps#72]
As detailed at https://developers.google.com/places/web-service/search, Google are deprecating the ability to use multiple types when performing Nearby Searches, but this API only offers a `Types` property on the `PlacesNearByRequest` which doesn't give me confidence that it has been updated accordingly. Multiple types will stop working on February 16, 2017. Is there are a plan to fix this?

**Comment by maximn** [comment]
You're welcome to issue a pull-request if you have an interest in it.

**Comment by peterdew** [comment]
@maximn, so this can be closed?
