### ISSUE TITLE
Ability to add referrer to request

### ISSUE THREAD

**Issue by jpspringall** [maximn/google-maps#74]
As Google allows a Referrer Authorization, would it be possible to add this functionality?

I've looked at the code, and it would that it would make sense to add it as parameter to the query function, in the same way that timeout is added.

And then when you create a new WebClientEx pass the extra parameter for referrer and follow the same logic as when passing the timeout.

**Comment by maximn** [comment]
Can you refer to the documentation of google?

**Comment by jpspringall** [comment]
Hi Maximn,

I'm not sure what you mean, but i have attached a screen shot of the google developer console, where you can set a referrer header
![api key](https://cloud.githubusercontent.com/assets/477087/22272313/65749e9c-e2ed-11e6-8e9b-0eb54df62e2b.PNG)

**Comment by jpspringall** [comment]
If i create a pull request, and make the change myself, do i need to create a branch, or do i just clone master?

**Comment by maximn** [comment]
OK, I get it. Sure you can add this option with a Pull Request.
You don't have to do branch. It's up to you.

**Comment by jpspringall** [comment]
Hi Maximn,

I've closed the repo, and made the changes.

Though When i come to push it back, it gives me a 403, do you need to give me permission?

Cheers

James

**Comment by jpspringall** [comment]
Hi Maxim,

Think i figured it out, you should have a pull request
