### ISSUE TITLE
Unable to query API behind proxy

### ISSUE THREAD

**Issue by TylerHaigh** [maximn/google-maps#77]
Hi there,
We're trying to use this library from behind a corporate proxy. Running the following throws a `The remote server returned an error: (407) Proxy Authentication Required.` exception.

How do we use this API from behind a proxy? Is there some way to configure the proxy?

```
using System;
using GoogleMapsApi;
using GoogleMapsApi.Entities.Directions.Request;
using GoogleMapsApi.Entities.Directions.Response;

namespace GoogleMapsApiTesting
{
    class Program
    {
        static void Main(string[] args)
        {

            //Static class use (Directions) (Can be made from static/instance class)
            DirectionsRequest directionsRequest = new DirectionsRequest()
            {
                Origin = "NYC, 5th and 39",
                Destination = "Philladephia, Chesnut and Wallnut",
            };

            DirectionsResponse directions = GoogleMaps.Directions.Query(directionsRequest);
            Console.WriteLine(directions);

        }
    }
}
```

**Comment by maximn** [comment]
Hi,

Currently, there's no such option.
If we add something like this it would have to be set here
https://github.com/maximn/google-maps/blob/99cf8593eb351104d71697f6d817d738a5177f6b/GoogleMapsApi/WebClientEx.cs#L24

Not sure how to pass it there.

Isn't there anyway to set the proxy on the Operating System level instead the app level?

**Comment by berinder** [comment]
Have you tried the solutions suggested here: http://stackoverflow.com/questions/2581609/the-remote-server-returned-an-error-407-proxy-authentication-required

**Comment by TylerHaigh** [comment]
Cheers, the following worked
```
<system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
    </defaultProxy>
  </system.net>
```

**Comment by valoricDe** [comment]
FYI this might be a google maps terms and conditions infringement: 10.1.1 (a) You must not access or use the Maps API(s) or any Content through any technology or means other than those provided in the Service, or through other explicitly authorized means Google may designate. For example, you must not access map tiles or imagery through interfaces or channels (including undocumented Google interfaces) other than the Maps API(s). https://developers.google.com/maps/terms
(taken from https://www.jscodetips.com/examples/is-it-possible-to-connect-the-google-maps-api-through-reverse-proxy-in-my-app)
