### ISSUE TITLE
Encoded Polyline based Static Maps

### ISSUE THREAD

**Issue by nilesh-shah** [maximn/google-maps#80]
Hello,
Google static maps allow rendering static maps based on encoded polylines. These polylines are part of the directions API response.

I have noticed that, when I request static map using locations, if route has multiple steps which are not joined by single road and has curved, static maps draw a single line to pinpoint the route which is not accurate. But for the same origin and destinations, If i fire the static map using encoded polyline, I get more accuracy in the routes display on the map.

I observed that the only way currently do build static map request is using locations using this library. Do we have a way where I can request or build static map URL using encoded polylines?

Thanks
Nilesh

**Comment by nilesh-shah** [comment]
I did check the code and suggesting below changes to implement "encoded polyline" based static map

1) In the overviewpolyline.cs, make below change to have the member publicly accessible to external assemblies

`[DataMember(Name = "points")]`
`public string EncodedPoints { get; internal set; }`

2) Add a new constructor of StaticMapRequest class which accepts only image size. This is because, when we request encoded polyline based static map, zoom and center location is not required to be passed. Pathes can be derived from EncodedPoints while requesting polyline based static map.

Let me know if with these changes, this feature can be made available in this library

Thanks
Nilesh

**Comment by maximn** [comment]
response on the PR #81

**Comment by nilesh-shah** [comment]
@maximn  I have posted my comments on PR #81

**Comment by baphamsts** [comment]
Hi @maximn  any method can I used to encoded an  ILocationString?

**Comment by maximn** [comment]
Nope :( Sorry
