### ISSUE TITLE
Convert to DateTime

### ISSUE THREAD

**Issue by LuizSD** [maximn/google-maps#84]
Can i convert the return text "1 min" to datetime? I was thinking make a string logical to do this, but all ways sounds bad.

Thx

**Comment by maximn** [comment]
maybe duration, no datetime

**Comment by LuizSD** [comment]
I convert using this:

public DateTime FormatDate(string time)
        {

            time = time.Replace(" hours ", ":");
            time = time.Replace(" hour ", ":");
            time = time.Replace(" mins", "");
            time = time.Replace(" min", "");

            if (time.Count() < 2)
                time = string.Format("0:{0}", time);

            return Convert.ToDateTime(time);
        }


But duration looks nice.
