### ISSUE TITLE
Photo's from Places text search not working

### ISSUE THREAD

**Issue by peterdew** [maximn/google-maps#85]
When I pull the code and run the unit-tests I got all unit tests working except the test from @pirvudoru  about photo's in a Places Text Search. 

Can't figure out why. Can somebody explain this? 

![image](https://cloud.githubusercontent.com/assets/27804639/25265679/7d3e3ea6-266e-11e7-9ed8-56593305ccd3.png)

**Comment by maximn** [comment]
Looks like you're right. I'm not sure if the problem with the test or the production code. I see this as well. I'll revert this last pull request
