### ISSUE TITLE
Description of setting the ApiKey

### ISSUE THREAD

**Issue by peterdew** [maximn/google-maps#87]
The description of setting the ApiKey in the wiki is confusing. 

It suggests to add it to the config-file like so: 

`<add key="ApiKey" value=""/> `
what made me think that the library will read and use this key from the config for all requests if available.

In fact the library doesn't work with that config-setting though, only the unittests does sometimes, like here: https://github.com/maximn/google-maps/blob/master/GoogleMapsApi.Test/IntegrationTests/DirectionsTests.cs#L198 and it puts the value manually into the requestobject.

But the unittest-project consúmes the library and isn't part of it. 

@maximn What is the best to do here and what is most in line with the original purpose of the project : 
    * reading the ApiKey from config and use it (for all requests? / requests that need an ApiKey?) like I expected? 
   * Change the documentation and instead tell to provide an ApiKey to the RequestObjects if needed?

**Comment by maximn** [comment]
https://github.com/maximn/google-maps/wiki (I've changed it a bit after your comment, but it's there.)
