### ISSUE TITLE
Supporting .net core

### ISSUE THREAD

**Issue by rhwilburn** [maximn/google-maps#94]
I am keen to use this library via .net core, and have started working on it. In fact I am almost done (70% unit test pass and the code compiles). I will make a PR when I am done. Hopefully this is something of interest to this project. I am making it dual compile into netstandard and net45 which means it can be written once but support both targets. Someone could add a PCL one if they really wanted probably fairly easily too.

I will need some help likely on the travis aspects; but will give it a stab myself.

I have had to change some API, so not sure on the preference there (I have tried not to mostly; but there is alot of duplication around the async stuff) and also removing references to webclient to support netcore.

Perhaps #55 will be fixed by this as we can add a very easy new target once standardized to netstandard.

**Comment by rhwilburn** [comment]
Perhaps #55 is related to this in a way. I suspect this may fix that issue but would need help testing that.

**Comment by rhwilburn** [comment]
Committed changeset: #96 for this. Please review

**Comment by rhwilburn** [comment]
This poses an interesting challenge: https://stackoverflow.com/questions/36398474/servicepointmanager-defaultconnectionlimit-in-net-core . I will try to handle this via a Task factory as opposed to at the http level

**Comment by maximn** [comment]
Published version 1.0.0 now. Can you verify that it works for you?
