### ISSUE TITLE
Can probably replace NUnit.Runners dependency with NUnit.ConsoleRunner

### ISSUE THREAD

**Issue by rhwilburn** [maximn/google-maps#97]
NUnit has been updated to move away from Nunit.Runners in favour of Nunit.Console.Runner

I propose we change this line:

`  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner`

to this line:

`  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner`

**Comment by maximn** [comment]
Create a Pull Request please, then we'll be able to see that it passes on Travis and merge.

**Comment by rhwilburn** [comment]
@maximn  Did the travis build work? Can we close this out?

**Comment by maximn** [comment]
Yes - https://travis-ci.org/maximn/google-maps
